### ISSUE TITLE
Temperature transition rates?

### ISSUE THREAD

**Issue by Billy-The-Squid** [noe98/Cayley#20]
The probability of a changed state in simulateTemp() is (1/2)(1-list_cache[-1][node number]*(tanh*β*J*NNs))

Since list_cache is all ones and zeroes (because it comes from sim_data, which uses that), if the node is empty, the transition rate should be just 1/2, right? Eq. 31 in Melin uses σ, which represents either 1 or -1. If I have somehow managed to avoid mistakes while reasoning through this, we need to adjust that, right? Convert by taking 2*(list_cache[-1][x])-1? Please do tell me what I overlooked here.

**Comment by pusztayj** [comment]
We should create a method that starts all nodes at 1 or -1. Then in the if statements within simulateTemp() we should have the state either change to a 1 or a -1.

**Comment by pusztayj** [comment]
Now there are new initial state methods to set all nodes to 1, -1, or randomly to one of the them. Also the simulate method itself has been changed, where in the if statements the state goes to 1 or -1 rather than 0 or 1.
